### ISSUE TITLE
Plugins - Provide multiple implementations

### ISSUE THREAD

**Issue by F-Lehmann** [Artemis-RGB/Artemis#499]
thoughts from Discord:
- Allow a plugin to provide multiple implementations
- Option to disable each implementation seperately
- Add a IPluginService interface for DI that is always available to the plugin as a singleton, regardless of what is enabled/disabled

That way you can put your shared logic 'outside' of your implementations and have them work induvidually from one another

**Comment by SpoinkyNL** [comment]
The first part of this is now committed and Artemis launches (but is very untested) with plugin 'features' now
![](https://i.imgur.com/HvOgYGs.png)

I also updated the plugins in a seperate branch so you can see the required changes
Its pretty minimal basically `EnablePlugin()` is just called `Enable()`, mostly just small changes to reflect that you are implementing a plugin feature, not just a plugin.

Plugins can now implement a `IPluginBootstrapper` if they want as well, this is the place to do any kind of initialization outside your features, like setting the config VM (the config VM is shared for the entire plugin, I figured if you want you can always add tabs)

You could still set the config VM when your brush/module/whatever gets enabled, but then it won't be populated until that specific _feature_ gets enabled. That's why doing it in the plugin bootstrapper is the best place now.

This is all going to be documented on the wiki ofcourse ^^
