### ISSUE TITLE
Rendering - Render scale causes some layer brushes to render incorrectly

### ISSUE THREAD

**Issue by diogotr7** [Artemis-RGB/Artemis#515]
The two worst examples i could find were with the Noise and Particle layers:
![hOt4VkGLYV](https://user-images.githubusercontent.com/29486064/101510257-9d6a2900-3971-11eb-9659-0712a4ba7386.gif)
![vUTsJRUwCf](https://user-images.githubusercontent.com/29486064/101510264-9f33ec80-3971-11eb-9109-88e1f9cf5c8a.gif)

The size of the noise and of each particle seems to ignore the size of the total bitmap, which causes, for example, the particles to look way too big when the render scale is set to a lower value.

**Comment by SpoinkyNL** [comment]
Fixed in https://github.com/Artemis-RGB/Artemis/commit/de951d9694b861d1f18bee925d2d1fe52772e75d

I simplified scaling a lot.. I don't know what I was thinking when I first implemented scaling but it was done very dumb. 
This does contain a breaking change for plugins that directly interact with the rectangles of LEDs/devices as they've been renamed from `RenderRectangle` to `Rectangle` and `AbsoluteRenderRectangle` to `AbsoluteRectangle`
