### ISSUE TITLE
SteelSeries Keyboard Layout 

### ISSUE THREAD

**Issue by ManfredRichthofen** [Artemis-RGB/Artemis#581]
![Screenshot 2021-04-12 015633](https://user-images.githubusercontent.com/46958197/114368614-6c258380-9b32-11eb-94b0-f8031ed65032.png)

**Comment by SpoinkyNL** [comment]
Hi there,

This isn't an issue but rather a missing layout. 
To learn more about layouts check out the [layouts wiki article](https://wiki.artemis-rgb.com/en/guides/developer/layouts). If you decide to create your own layout, feel free to share it via a PR or on Discord so that others may enjoy it too :)
