### ISSUE TITLE
Updates pushing through Full Screen app

### ISSUE THREAD

**Issue by r3m0dul8** [Artemis-RGB/Artemis#596]
Hi Guys

Not sure if you were aware or not but I just had a update come through when I was in a full screen app (got annihilated in WarZone because of the update :D )

Any chance that can be fixed so it doesn't happen when you're in a full screen app?

Thanks

Dave

**Comment by SpoinkyNL** [comment]
Hey,

I've changed it so that Artemis won't attempt to auto-install updates anymore.
Instead, the notification dialog has been updated to display a button which when clicked will immediately install the update.
![image](https://user-images.githubusercontent.com/8858506/121508336-c5504d00-c9e5-11eb-9607-e41ff9ab9ff0.png)

These notifications use whatever notification settings you have set up in Windows, and by default that means they won't show during fullscreen gameplay
