### ISSUE TITLE
How to export profiles and settings before updating to 20220923.3

### ISSUE THREAD

**Issue by Y4m4k** [Artemis-RGB/Artemis#727]
Hi - I have spent a lot of time customizing my LED profiles and building new led stripes profiles using RGB Layout Center. Is there a way to export/save these settings before upgrading and wiping all my RGB schemes and settings? I am currently on build # 20220715.1. Any guidance is highly appreciated.

**Comment by RobertBeekman** [comment]
Hi,

There is no way to import those profiles into the new update, otherwise the installer would not have wiped the settings.
I don't know if you are using custom device layouts, those are still compatible (and won't be deleted)


One thing that might help you is downloading a special version of the old Artemis which can run alongside the new version.
This way you won't lose your old profiles and you can rebuild them runnign both versions side-by-side.

# Artemis WPF Builds
https://builds.artemis-rgb.com/binaries/wpf
This directory contains WPF builds of Artemis.  
WPF is the old UI framework, no longer used by newer versions of Artemis. These builds are Windows-only.

These builds use a different data directory in order to allow running them alongside new Avalonia builds, useful to recreate your profiles.

## Usage
1. Rename `C:\ProgramData\Artemis` to `C:\ProgramData\Artemis.WPF`
2. Extract the ZIP anywhere
3. Run Artemis.UI.exe
4. You can now download the installer and run it to install the new version https://builds.artemis-rgb.com/binaries/Artemis.Installer.exe

**Comment by Y4m4k** [comment]
Thanks for the info @RobertBeekman !
