### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CuteistCat** [Artemis-RGB/Artemis#828]
WHat is the resoning behind useing a nonfree license(i would want u to change it but i dont think that will hapen)

**Comment by CuteistCat** [comment]
also the website says its opensourcce but it dosent comply with the OSI`s definition

**Comment by RobertBeekman** [comment]
Hello,

The license was chosen because I have no interest in others using Artemis, or parts of it, for commercial purposes. In my opinion FOSS is too idealistic in that regard. 

As for the website it states that it is open-source which I believe to be true, the source is openly available. If you feel that somehow ties us to how the OSI defines open-source than I suppose it does not hurt to clarify this on the website and merely state the source is available.

I hope this answers your question :)

**Comment by CuteistCat** [comment]
say "source avalible"
